name: tensorflow_lite
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  tensorflow_lite_flutter: ^2.0.1
  fl_chart: ^0.68.0
  # Firebase dependencies
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  camera: ^0.11.0+1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  path: ^1.8.1
  fluttertoast: ^8.0.8
  google_sign_in: ^6.2.1
  eva_icons_flutter: ^3.1.0
  introduction_screen: ^3.1.14
  mrx_charts: ^0.1.3
  http: ^1.2.1

dependency_overrides:
  path_provider_android: 2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    # - assets/newlabels.txt
    - assets/labels.txt
    # - assets/model_waste_detection.tflite
    - assets/ai_rice_trained_model.tflite
    - lib/style.dart
