// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCHCm6uNiZtfPXVUEGtkdWdQfXKdOP5nY',
    appId: '1:420162653985:web:f2fa11e50dee99650d3860',
    messagingSenderId: '420162653985',
    projectId: 'tensorflowlite-c3e51',
    authDomain: 'tensorflowlite-c3e51.firebaseapp.com',
    storageBucket: 'tensorflowlite-c3e51.appspot.com',
    measurementId: 'G-KXMD2NZ5JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwnJ556BF6cbcnSRDOQ4RTqnt7T4o7g5M',
    appId: '1:420162653985:android:a4b01f28b5fb63800d3860',
    messagingSenderId: '420162653985',
    projectId: 'tensorflowlite-c3e51',
    storageBucket: 'tensorflowlite-c3e51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUW7GA-2Zpa1FMjve9bnVVlItFoV1WBJQ',
    appId: '1:420162653985:ios:c3718a7ca7f195810d3860',
    messagingSenderId: '420162653985',
    projectId: 'tensorflowlite-c3e51',
    storageBucket: 'tensorflowlite-c3e51.appspot.com',
    iosBundleId: 'com.example.tensorflowLite',
  );
}
